export const SOCKET_EVENTS = {
    CONNECTION: "connection",
    DISCONNECT: "disconnect",
    REGISTER: "register",
    CREATE_ROOM: "createRoom",
    HOST_ROOM: "hostRoom",
    JOIN_ROOM: "joinRoom",
    START_GAME: "startGame",
    START_GAME_RESPONSE: "startGameResponse",
    ENQUIRY: "enquiry",
    LEAVE_ROOM: "leaveRoom",
    NEW_MESSAGE: "newMessage",
    NEW_USER: "newUser",
    MESSAGE_SEND: "messageSend",
    MESSAGE_RECEIVE: "messageReceive",
    USER_TYPING: "userTyping",
    USER_STOPPED_TYPING: "userStoppedTyping",
    NO_OF_USERS: "noOfUsers",
    ANNOUNCE: "announce",
    HOSTING_RESPONSE: "hostingResponse",
    JOINING_RESPONSE:"joiningResponse",
    REGISTRATION_RESPONSE: "registrationResponse",
    CREATE_ROOM_RESPONSE: "createRoomResponse",
    ENQUIRY_RESPONSE: "enquiryResponse",
    ROOM_FULL: "roomFull",
    ERROR: "error",
} as const;
